### ISSUE TITLE
eNodeB's stats

### ISSUE THREAD

**Issue by PrimalMight** [PrimalMight/KPM-Project#2]
eNode 0 Stats:

Downlink BW: 100

Uplink BW: 100

Downlink Earfcn: 100

Uplink Earfcn: 18100

TxPower UE: 10

---------------------------

eNode 1 Stats:

Downlink BW: 100

Uplink BW: 100

Downlink Earfcn: 100

Uplink Earfcn: 18100

TxPower UE: 10

---------------------------

eNode 2 Stats:

Downlink BW: 100

Uplink BW: 100

Downlink Earfcn: 100

Uplink Earfcn: 18100

TxPower UE: 10

---------------------------

This should be different for each eNodeB ??
If so -> FIX
if not -> close issue

**Comment by sedemto** [comment]
don't know, i think it's on us, same stats seems fine
