### ISSUE TITLE
commit: 19a52e2 - what the fuck is flow 3 and 4

### ISSUE THREAD

**Issue by PrimalMight** [PrimalMight/KPM-Project#3]
------------------------------------------------

Flow ID: 3

Src add: 7.0.0.6-> Dst add: 7.0.0.6

Src port: 49153-> Dst port: 21

Tx Packets/Bytes: 3/168

Rx Packets/Bytes: 3/168

Throughput: 0.145833kb/s

Delay sum: 0ms

Mean delay: 0ms

Jitter sum: 0ms

Mean jitter: 0ms

Lost Packets: 0

Packet loss: 0%

------------------------------------------------

Flow ID: 4

Src add: 7.0.0.6-> Dst add: 7.0.0.6

Src port: 21-> Dst port: 49153

Tx Packets/Bytes: 3/120

Rx Packets/Bytes: 3/120

Throughput: 0.104167kb/s

Delay sum: 0ms

Mean delay: 0ms

Jitter sum: 0ms

Mean jitter: 0ms

Lost Packets: 0

Packet loss: 0%

------------------------------------------------

????

**Comment by slimakk** [comment]
Missing PacketSinkApplication as FTP client and wrong IP address in the FTP server socket. Fixed in commit: [28ca8ec](https://github.com/PrimalMight/KPM-Project/commit/28ca8ec1021359b2e204fd3ee3afff4323e07ce2)
